<?php
namespace Source\Models;

use CoffeeCode\DataLayer\DataLayer;
use Exception;

class User extends DataLayer
{
    public $type;

    public function __construct()
    {
        parent::__construct("users", ["first_name", "last_name", "email", "passwd"]);
    }

    public function bootstrap(
        string $first_name,
        string $last_name,
        string $email,
        string $passwd): User
    {
       $this->first_name = $first_name;
       $this->last_name = $last_name;
       $this->email = $email;
       $this->passwd = passwd_hash($passwd);
       return $this;
    }

    public function save(): bool
    {
        if (!$this->validateEmail() || !parent::save())
        {
            return false;
        }
        return parent::save(); // TODO: Change the autogenerated stub
    }

    protected function validateEmail(): bool
    {
        if (empty($this->email) || !is_email($this->email))
        {
            $this->type = "info";
            $this->fail = new Exception("Informe um email válido");
            return false;
        }

        $userRegistered = null;
        if (!$this->id)
        {
            $userRegistered = $this->find("email = :email", "email={$this->email}")->count();
        }else{
            $userRegistered = $this->find("email = :email AND id != :id", "email={$this->email}&id={$this->id}")->count();
        }

        if ($userRegistered)
        {
            $this->type = "error";
            $this->fail = new Exception("O email informado já existe");
            return false;
        }
        return true;
    }
}